--CREATING A SCHEMA 
CREATE SCHEMA SOURCE_DATA;

--CREATING A TABLE
CREATE TABLE SOURCE_DATA.DAILY_PRICING(

PRODUCT_GROUP_NAME VARCHAR(100),
PRODUCT_NAME VARCHAR(100),
STATE_NAME VARCHAR(100),
MARKET_CENTER VARCHAR(100),
ARRIVALS_IN_TONNES DECIMAL(12,2),
UNIT_OF_ARRAIVALS CHAR(100),
ORIGIN VARCHAR(100),
VARIETY VARCHAR(100),
MAXIMUM_PRICE_IN_RS_QUINTALS DECIMAL(12,2),
MINIMUM_PRICE_IN_RS_QUINTALS DECIMAL(12,2),
MODAL_PRICE_IN_RS_QUINTALS DECIMAL(12,2),
UNIT_OF_PRICE CHAR(100)
)

--ALTER TABLE
ALTER TABLE SOURCE_DATA.DAILY_PRICING ADD PRICE_DATE DATE
 
 --ISERTING DATA IN TABLE
 INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
 
 'PULSES',
 'ALASANDE GRAM',
 'KARNATAKA',
 'BADAMI',
 7,
 'TONNES',
 'NR',
 'ALASANDE GRAM',
 5700,
 5700,
 5700,
 'RS/QUINTALS',
 '01/10/2019'
 )
 INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
 
 'PULSES',
 'ALASANDE GRAM',
 'KARNATAKA',
 'HUBALI(AMARAGOL)',
 5,
 'TONNES',
 'NR',
 'ALASANDE GRAM',
 5620,
 5620,
 5620,
 'RS/QUINTALS',
 '01/10/2019'
 )
 INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
  
 'PULSES',
 'ARHAR(TUR/RED GRAM)(WHOLE)',
 'ANDHARA PRADESH',
 'KURNOOL',
 0.2,
 'TONNES',
 'NR',
 'LOCAL',
 5910,
 5910,
 5910,
 'RS/QUINTALS',
 '01/10/2019'
 )
 INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
  
 'PULSES',
 'ARHAR(TUR/RED GRAM)(WHOLE)',
 'CHATTISGAR',
 'KAWARDHA',
 1.8,
 'TONNES',
 'NR',
 'OTHERS',
 6250,
 6000,
 6000,
 'RS/QUINTALS',
 '01/10/2019'
 )
 INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
  
 'PULSES',
 'ARHAR(TUR/RED GRAM)(WHOLE)',
 'GUJARAT',
 'AMRELI',
 4.7,
 'TONNES',
 'NR',
 'HYBRID',
 5650,
 3000,
 5095,
 'RS/QUINTALS',
 '01/10/2019'
 )
 INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
 
 'PULSES',
 'ARHAR(TUR/RED GRAM)(WHOLE)',
 'GUJRAT',
 'BHILODA',
  0.01,
 'TONNES',
 'NR',
 'OTHER',
  5500,
  5250,
  5000,
 'RS/QUINTALS',
 '01/10/2019'

 )
 INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
 'PULSES',
 'ARHAR(TUR/RED GRAM)(WHOLE)',
 'GUJRAT',
 'BOTAD',
  3.6,
 'TONNES',
 'NR',
 'OTHER',
  5455,
  5250,
  5855,
  'RS/QUINTALS',
  '01/10/2019'
    )
INSERT INTO SOURCE_DATA .DAILY_PRICING VALUES(

'PLUSES',
'ARHAR(TUR/RED GRAM)(WHOLE)',
'GUJARAT',
'DAHOD',
 7.7,
'TONNES',
'NR',
'ARHAR(WHOLE)',
5100,
4800,
5000,
'RS/QUINTALS',
'01/01/2019'
)
INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
'PULSES',
'ARHAR(TUR/RED GRAM)(WHOLE)',
'GUJRAT',
'DHORAJ',
3.2,
'TONNES',
'NR',
'MEDIUM',
 5400,
 5000,
 5000,
 'RS/QUINTALS',
 '01/01/2019'
)
INSERT INTO SOURCE_DATA.DAILY_PRICING VALUES(
'PULSES',
'ARHAR(TUR/RED GRAM)(WHOLE)',
'KERALA',
'PALAKKAAD',
 1,
'TONNES',
'NR',
'ARHAR DAL(TUR)',
 11000,
 10000,
 10600,
 'RS/QUINTALS',
 '01/01/2019'
)